from __future__ import annotations
from abc import ABC, abstractmethod

class Worker(ABC):
    @abstractmethod
    def start(self) -> None: ...
    @abstractmethod
    def stop(self) -> None: ...
    @abstractmethod
    def apply_update(self, *args, **kwargs) -> None: ...
    @abstractmethod
    def graceful_restart(self, *args, **kwargs) -> None: ...
