site_name: Frigate Hot-Reload
site_url: https://josifbg.github.io/frigate-hotreload/
repo_url: https://github.com/josifbg/frigate-hotreload
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - search.highlight
    - search.suggest
nav:
  - Overview: index.md
  - Quickstart: quickstart.md
  - Installation: install.md
  - Configuration: configuration.md
  - Cameras: cameras.md
  - API: api.md
  - UI: ui.md
  - Troubleshooting: troubleshooting.md
  - Changelog: changelog.md
  - Roadmap: roadmap.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
