site_name: Frigate Hot-Reload
site_url: http://127.0.0.1:8000/
repo_url: https://github.com/josifbg/frigate-hotreload

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - search.highlight
    - search.suggest

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - API: api.md
  - UI Guide: ui.md
  - Configuration: configuration.md
  - Cameras: cameras.md
  - Examples: examples.md
  - Security: security.md
  - FAQ: faq.md
  - Troubleshooting: troubleshooting.md
  - Roadmap: roadmap.md
  - Changelog: ../CHANGELOG.md
